[package]
name = "egui_reflect"
version = "0.0.0"
edition = "2021"

[dependencies]
egui = { version = "0.29", default-features = false }
rustc-hash = "2.0.0"
egui_reflect_derive = { path = "derive" }

glam = { version = "0.29.0", optional = true }
